[tox]
envlist =
    py{310}-dj{32,42}
    py{310,311,312}-dj{32,42}
    py{312, 313, 314}-dj{52,60,main}

[testenv]
usedevelop = true
extras = embedding,tests
commands =
    playwright install chromium
    pytest --cov=feincms3_cookiecontrol --cov-report=term-missing tests/testapp {posargs}
deps =
    dj32: Django>=3.2,<4.0
    dj42: Django>=4.2,<5.0
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    djmain: https://github.com/django/django/archive/main.tar.gz

# [testenv:docs]
# deps =
#     Sphinx
#     sphinx-rtd-theme
#     Django
# changedir = docs
# commands = make html
# skip_install = true
# allowlist_externals = make
