# Generated by Django 3.2.7 on 2021-09-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='technical name')),
                ('title_de', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('title_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('title_it', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('description_de', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, verbose_name='description')),
                ('description_it', models.TextField(blank=True, verbose_name='description')),
                ('preselect', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'cookie category',
                'verbose_name_plural': 'cookie categories',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='CookieScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True, verbose_name='technical name')),
                ('inject_if', models.TextField(blank=True, help_text='inject if cookie group is accepted', verbose_name='inject if')),
                ('inject_else', models.TextField(blank=True, help_text='inject if cookie group is denied', verbose_name='inject else')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feincms3_cookiecontrol.cookiecategory')),
            ],
            options={
                'verbose_name': 'cookie script',
                'verbose_name_plural': 'cookie scripts',
                'ordering': ('name',),
            },
        ),
    ]
